approot/src/WebController/Controllers/DashboardController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Configuration;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.DashboardObserver)]
    public class DashboardController : Controller
    {
        const string MAIN_PANEL_ID = "Main";
        const string HOME_PANEL_ID = "Home";

        private UiNodesEngine engine = SystemController.uiNodesEngine;


        public IActionResult Index()
        {
            ViewBag.panelId = HOME_PANEL_ID;

            return View();
        }



        public IActionResult Panel(string id)
        {
            if (engine == null)
                return HttpBadRequest();

            if (id == null || id == MAIN_PANEL_ID)
            {
                id = MAIN_PANEL_ID;
                ViewBag.panelName = "Main Panel";
            }
            else
            {
                PanelNode panel = engine.GetPanel(id);
                if (panel == null)
                    return HttpNotFound();
                ViewBag.panelName = panel.Settings["Name"].Value;
            }

            ViewBag.panelId = id;
            return View("Index");
        }

        public IActionResult List()
        {
            if (engine == null)
                return HttpBadRequest();

            ViewBag.showMainPanel = engine.GetUINodesForPanel(MAIN_PANEL_ID).Any();

            List<PanelNode> allPanels = engine.GetPanels();
            List<PanelNode> notEmptyPanels = new List<PanelNode>();
            foreach (var panel in allPanels)
            {
                if (engine.GetUINodesForPanel(panel.Id).Any())
                    notEmptyPanels.Add(panel);
            }

            return View(notEmptyPanels);
        }


        
        public IActionResult Chart(string id, string autoscroll, string style, string start, string end)
        {
            if (engine == null)
                return HttpBadRequest();

            UiChartNode node = engine.GetUINode(id) as UiChartNode;
            if (node == null)
                return new HttpNotFoundResult();

            ViewBag.autoscroll = autoscroll;

            if (style == null)
                style = node.Style;

            ViewBag.style = style;
            ViewBag.start = start ?? "0";
            ViewBag.end = end ?? "0";
            ViewBag.panelId = node.PanelId;

            return View(node);
        }
    }
}

approot/src/WebController/Controllers/UITimerController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.DashboardObserver)]

    public class UITimerController : Controller
    {
        private NodesEngine engine;

        const string ERROR_MESSAGE= "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>";


        public UITimerController()
        {
            engine = SystemController.nodesEngine;
        }

        public ActionResult Tasks(string id)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;

            if (node == null)
                return HttpNotFound();

            ViewBag.NodeId = node.Id;
            ViewBag.Name = node.Settings["Name"].Value;

            List<UITimerTask> tasks = node.GetAllTasks();

            return View(tasks);
        }


        [Authorize(UserClaims.DashboardEditor)]

        [HttpGet]
        public ActionResult New(string id)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            ViewBag.NodeId = node.Id;
            ViewBag.Name = node.Settings["Name"].Value;

            UITimerTask task = new UITimerTask
            {
                NodeId = id,
                ExecutionDate = DateTime.Now,
                RepeatingInterval = 1000,
                Enabled = true
            };

            return View(task);
        }


        [Authorize(UserClaims.DashboardEditor)]

        [HttpPost]
        public ActionResult New(UITimerTask task)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(task.NodeId) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            node.AddTask(task);

            return RedirectToAction("Tasks", new { id = task.NodeId});
        }


        [Authorize(UserClaims.DashboardEditor)]

        [HttpGet]
        public ActionResult Edit(string id, int id2)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            UITimerTask task = node.GetTask(id2);
            if (task == null)
                return HttpNotFound();

            ViewBag.Name = node.Settings["Name"].Value;

            return View(task);
        }


        [Authorize(UserClaims.DashboardEditor)]

        [HttpPost]
        public ActionResult Edit(UITimerTask task,int TaskId)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            task.Id = TaskId; //pasing id dont work!
            UiTimerNode node = engine.GetNode(task.NodeId) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            node.UpdateTask(task);

            return RedirectToAction("Tasks", new { id = task.NodeId });
        }


        [Authorize(UserClaims.DashboardEditor)]

        public ActionResult Remove(string id, int id2)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            node.RemoveTask(id2);

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("Tasks");
        }


        [Authorize(UserClaims.DashboardEditor)]

        public ActionResult Enable(string id, int id2)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            UITimerTask task = node.GetTask(id2);
            if (task == null)
                return HttpNotFound();

            task.Enabled = true;

            node.UpdateTask(task);

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("Tasks");
        }

        [Authorize(UserClaims.DashboardEditor)]

        public ActionResult Disable(string id, int id2)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            UITimerTask task = node.GetTask(id2);
            if (task == null)
                return HttpNotFound();

            task.Enabled = false;

            node.UpdateTask(task);

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("Tasks");
        }


        [Authorize(UserClaims.DashboardEditor)]

        public ActionResult ExecuteNow(string id, int id2)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            node.ExecuteNowTask(id2);

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("Tasks");
        }


        [Authorize(UserClaims.DashboardEditor)]

        public ActionResult RemoveAll(string id)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            node.RemoveAllTasks();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("Tasks");
        }



        [Authorize(UserClaims.DashboardEditor)]

        public ActionResult RemoveCompleted(string id)
        {
            if (engine == null)
                return View("Error", ERROR_MESSAGE);

            UiTimerNode node = engine.GetNode(id) as UiTimerNode;
            if (node == null)
                return HttpNotFound();

            node.RemoveCompletedTasks();

            if (Request.Headers["Referer"].Any())
                return Redirect(Request.Headers["Referer"].ToString());
            else return RedirectToAction("Tasks");
        }


    }
}

approot/src/WebController/Views/UITimer/Edit.cshtml
@using MyNodes.Nodes
@model MyNodes.Nodes.UITimerTask

@{
    ViewBag.Title = ViewBag.Name;

    string repeatingPanelDisplay = Model.IsRepeating ? "" : "display: none";
    string nonRepeatingPanelDisplay = Model.IsRepeating ? "display: none" : "";
}

<br />
<div class="ui container">

    <h2>@ViewBag.Title</h2>
    <div>
        < <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
        < <a asp-controller="UITimer" asp-action="Tasks" asp-route-id="@Model.NodeId">Tasks</a>
    </div>
    <div class="ui divider"></div>

    <div class="ui two column stackable centered grid">
        <div class="column">
            <div class="ui raised segments">
                <div class="ui secondary segment">
                    <h4>Edit Task @Model.Id</h4>
                </div>

                <form asp-action="Edit" asp-anti-forgery="true" class="ui form">
                    <div class="ui attached segment">

                        <input type="hidden" id="Id" name="Id" value=@Model.Id />
                        <input type="hidden" id="TaskId" name="TaskId" value=@Model.Id />
                        <input type="hidden" asp-for="NodeId" />
                        <input type="hidden" asp-for="Enabled" />

                        <div class="validation" asp-validation-summary="ValidationSummary.All"></div>

                        <div class="field">
                            <label>Task description</label>
                            <input type="text" asp-for="Description">
                        </div>

                        <div class="field">
                            <label>Execution date</label>
                            <input type="text" asp-for="ExecutionDate">
                        </div>

                        <div class="field">
                            <div class="ui toggle checkbox">
                                <input asp-for="IsRepeating">
                                <label>Repeat task</label>
                            </div>
                        </div>





                        <div id="nonRepeatingPanel" style="@nonRepeatingPanelDisplay">
                            <div class="field">
                                <label>Set value</label>
                                <input type="text" asp-for="ExecutionValue">
                            </div>
                        </div>

                        <div id="repeatingPanel" style="@repeatingPanelDisplay">
                            <div class="fields">
                                <div class="field">
                                    <label>Repeat A value</label>
                                    <input type="text" asp-for="RepeatingAValue">
                                </div>

                                <div class="field">
                                    <label>Repeat B value</label>
                                    <input type="text" asp-for="RepeatingBValue">
                                </div>
                            </div>
                            <div class="fields">

                                <div class="field">
                                    <label>Repeat count (0 for infinity)</label>
                                    <input type="text" asp-for="RepeatingNeededCount">
                                </div>

                                <div class="field">
                                    <label>Repeat interval (ms)</label>
                                    <input type="text" asp-for="RepeatingInterval">
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="ui center aligned attached segment">
                        <div class="ui centered  buttons">
                            <a asp-action="Tasks" asp-route-id="@Model.NodeId" class="ui button">Cancel</a>
                            <input type="submit" value="Save" class="ui primary button" />
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>




@section scripts
{

    <script>
        var fade = 500;


        $("#IsRepeating").click(function () {
            if ($(this).is(":checked")) {
                $('#repeatingPanel').fadeIn(fade);
                $('#nonRepeatingPanel').hide();
            } else {
                $('#repeatingPanel').hide();
                $('#nonRepeatingPanel').fadeIn(fade);
            }
        });

        $(function () {
            $('#ExecutionDate').daterangepicker({
                format: 'DD.MM.YYYY HH:mm:ss',
                "singleDatePicker": true,
                "timePicker": true,
                "timePickerIncrement": 1,
                "timePicker12Hour": false,
                "timePickerSeconds": true
            });
        });
    </script>
}

approot/src/WebController/Views/UITimer/New.cshtml
@using MyNodes.Nodes
@model MyNodes.Nodes.UITimerTask

@{
    ViewBag.Title = ViewBag.Name;

    string repeatingPanelDisplay = Model.IsRepeating ? "" : "display: none";
    string nonRepeatingPanelDisplay = Model.IsRepeating ? "display: none" : "";
}

<br />
<div class="ui container">

    <h2>@ViewBag.Title</h2>
    <p>
        < <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
        < <a asp-controller="UITimer" asp-action="Tasks" asp-route-id="@Model.NodeId">Tasks</a>

    </p>
    <div class="ui divider"></div>

    <div class="ui two column stackable centered grid">
        <div class="column">
            <div class="ui raised segments">
                <div class="ui secondary segment">
                    <h4>New Task</h4>
                </div>

                <form asp-action="New" asp-anti-forgery="true" class="ui form">
                    <div class="ui attached segment">

                        <input type="hidden" asp-for="NodeId" />
                        <input type="hidden" asp-for="Enabled" />

                        <div class="validation" asp-validation-summary="ValidationSummary.All"></div>

                        <div class="field">
                            <label>Task description</label>
                            <input type="text" asp-for="Description">
                        </div>

                        <div class="field">
                            <label>Execution date</label>
                            <input type="text" asp-for="ExecutionDate">
                        </div>

                        <div class="field">
                            <div class="ui toggle checkbox">
                                <input asp-for="IsRepeating">
                                <label>Repeat task</label>
                            </div>
                        </div>





                        <div id="nonRepeatingPanel" style="@nonRepeatingPanelDisplay">
                            <div class="field">
                                <label>Set value</label>
                                <input type="text" asp-for="ExecutionValue">
                            </div>
                        </div>

                        <div id="repeatingPanel" style="@repeatingPanelDisplay">
                            <div class="fields">
                                <div class="field">
                                    <label>Repeat A value</label>
                                    <input type="text" asp-for="RepeatingAValue">
                                </div>

                                <div class="field">
                                    <label>Repeat B value</label>
                                    <input type="text" asp-for="RepeatingBValue">
                                </div>
                            </div>
                            <div class="fields">

                                <div class="field">
                                    <label>Repeat count (0 for infinity)</label>
                                    <input type="text" asp-for="RepeatingNeededCount">
                                </div>

                                <div class="field">
                                    <label>Repeat interval (ms)</label>
                                    <input type="text" asp-for="RepeatingInterval">
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="ui center aligned attached segment">
                        <div class="ui buttons">
                            <a asp-action="Tasks" asp-route-id="@Model.NodeId" class="ui button">Cancel</a>
                            <input type="submit" value="Create" class="ui primary button" />
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>




@section scripts
{

<script>
        var fade = 500;


        $("#IsRepeating").click(function () {
            if ($(this).is(":checked")) {
                $('#repeatingPanel').fadeIn(fade);
                $('#nonRepeatingPanel').hide();
            } else {
                $('#repeatingPanel').hide();
                $('#nonRepeatingPanel').fadeIn(fade);
            }
        });

        $(function () {
            $('#ExecutionDate').daterangepicker({
                format: 'DD.MM.YYYY HH:mm:ss',
                "singleDatePicker": true,
                "timePicker": true,
                "timePickerIncrement": 1,
                "timePicker12Hour": false,
                "timePickerSeconds": true
            });
        });
</script>
}

approot/src/WebController/Views/UITimer/Tasks.cshtml
@using MyNodes.Nodes
@model IEnumerable<MyNodes.Nodes.UITimerTask>


@{
    ViewBag.Title = ViewBag.Name;
}



    <br />
<div class="ui container">


    <h2>@ViewBag.Title</h2>
    <p>
        < <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </p>
    <div class="ui divider"></div>

    <div class="ui raised segments">
        <div class="ui secondary clearing segment">
            <b>Tasks</b>
            <a asp-action="New" asp-route-id="@ViewBag.NodeId" class="ui right floated small primary button">New Task</a>
        </div>
        @if (Model == null || Model.Count() == 0)
        {
            <div class="ui attached segment">
                No tasks
            </div>
        }
        else
        {
            foreach (var task in Model)
            {
                <div class="ui attached clearing segment">


                    <h4>
                        Task @task.Id
                        @if (task.Description != null)
                        {
                            @: : @task.Description
                        }
                    </h4>
                    <div class="ui right floated basic tiny buttons">
                        @if (!task.IsCompleted)
                        {
                            if (task.Enabled)
                            {
                                <a asp-action="Disable" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Disable</b></a>
                            }
                            else
                            {
                                <a asp-action="Enable" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Enable</b></a>
                            }

                            if (task.IsRepeating)
                            {
                                <a asp-action="ExecuteNow" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Restart</b></a>
                            }
                            else
                            {
                                <a asp-action="ExecuteNow" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Execute</b></a>
                            }
                        }
                        else
                        {
                            if (task.IsRepeating)
                            {
                                <a asp-action="ExecuteNow" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Restart</b></a>
                            }
                            else
                            {
                                <a asp-action="ExecuteNow" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Execute</b></a>
                            }
                        }
                        <a asp-action="Edit" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Edit</b></a>
                        <a asp-action="Remove" class="ui button" asp-route-id="@ViewBag.NodeId" asp-route-id2="@task.Id"><b>Delete</b></a>
                    </div>

                    @if (task.IsCompleted)
                    {
                        <span class="ui tiny green ribbon label">COMPLETED</span>
                    }
                    else if (!task.Enabled)
                    {
                        <span class="ui tiny ribbon label">DISABLED</span>
                    }
                    else
                    {
                        <span class="ui tiny blue ribbon label">ACTIVE</span>
                    }
                    <br />
                    <br />

                    Execution date: @task.ExecutionDate<br>
                    Set value:@task.ExecutionValue<br>
                    @if (task.IsRepeating)
                    {
                        @:Repeat values: @task.RepeatingAValue / @task.RepeatingBValue<br>
                        @:Repeat interval: @task.RepeatingInterval<br>
                        @:Executions done:@task.RepeatingDoneCount<br>
                        if (task.RepeatingNeededCount > 0)
                        {
                            @:Executions left:@(task.RepeatingNeededCount - task.RepeatingDoneCount)<br>
                        }

                    }
                </div>
            }
            <div class="ui right aligned attached segment">
                <div class="ui small buttons">
                    <a asp-action="RemoveAll" asp-route-id="@ViewBag.NodeId" class="ui button">Delete all</a>
                    <a asp-action="RemoveCompleted" asp-route-id="@ViewBag.NodeId" class="ui primary button">Delete completed</a>
                </div>
            </div>
        }
    </div>
</div>

<br />