approot/src/WebController/Controllers/ConfigController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.PlatformAbstractions;
using MyNodes.Users;
using MyNodes.WebController.Code;
using MyNodes.WebController.ViewModels.Config;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.ConfigObserver)]
    public class ConfigController : Controller
    {

        private const string SETTINGS_FILE_NAME = "appsettings.json";
        private string settings_file;
        private string project_file;
        private IConfigurationRoot configuration;

        public ConfigController(IConfigurationRoot configuration, IApplicationEnvironment appEnv)
        {
            this.configuration = configuration;
            string applicationPath = appEnv.ApplicationBasePath;
            settings_file = Path.Combine(applicationPath, SETTINGS_FILE_NAME);
            project_file = Path.Combine(applicationPath, "project.json");
        }

        private dynamic ReadConfig()
        {
            return JObject.Parse(System.IO.File.ReadAllText(settings_file));
        }

        private void WriteConfig(dynamic config)
        {
            System.IO.File.WriteAllText(settings_file, config.ToString());
        }

        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public IActionResult SerialGateway()
        {
            ViewBag.ports = SerialConnectionPort.GetAvailablePorts();

            return View(new SerialGatewayViewModel
            {
                PortName = SystemController.gatewayConfig.SerialGatewayConfig.SerialPortName,
                Boudrate = SystemController.gatewayConfig.SerialGatewayConfig.Boudrate
            });
        }


        [Authorize(UserClaims.ConfigEditor)]

        [HttpPost]
        public IActionResult SerialGateway(SerialGatewayViewModel model)
        {
            if (String.IsNullOrEmpty(model.PortName))
                return RedirectToAction("SerialGateway");

            dynamic json = ReadConfig();
            json.Gateway.SerialGateway.SerialPortName = model.PortName;
            json.Gateway.SerialGateway.Boudrate = model.Boudrate;
            WriteConfig(json);
            configuration.Reload();

            SystemController.DisconnectGateway();
            SystemController.gatewayConfig.SerialGatewayConfig.SerialPortName = model.PortName;
            SystemController.gatewayConfig.SerialGatewayConfig.Boudrate = model.Boudrate;

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult EthernetGateway()
        {
            EthernetGatewayViewModel model = new EthernetGatewayViewModel
            {
                Ip = SystemController.gatewayConfig.EthernetGatewayConfig.GatewayIP,
                Port = SystemController.gatewayConfig.EthernetGatewayConfig.GatewayPort
            };

            return View(model);
        }


        [Authorize(UserClaims.ConfigEditor)]

        [HttpPost]
        public IActionResult EthernetGateway(EthernetGatewayViewModel model)
        {
            dynamic json = ReadConfig();
            json.Gateway.EthernetGateway.GatewayIP = model.Ip;
            json.Gateway.EthernetGateway.GatewayPort = model.Port;
            WriteConfig(json);
            configuration.Reload();

            SystemController.DisconnectGateway();
            SystemController.gatewayConfig.EthernetGatewayConfig.GatewayIP = model.Ip;
            SystemController.gatewayConfig.EthernetGatewayConfig.GatewayPort = model.Port;

            return RedirectToAction("Index");
        }


        [Authorize(UserClaims.ConfigEditor)]

        public async Task<bool> ConnectSerialGateway()
        {
            SystemController.DisconnectGateway();

            dynamic json = ReadConfig();
            json.Gateway.SerialGateway.Enable = true;
            json.Gateway.EthernetGateway.Enable = false;
            WriteConfig(json);
            configuration.Reload();

            SystemController.gatewayConfig.SerialGatewayConfig.Enable = true;
            SystemController.gatewayConfig.EthernetGatewayConfig.Enable = false;

            await Task.Run((() =>
            {
                SystemController.ConnectToGateway();
            }));

            return true;
        }



        [Authorize(UserClaims.ConfigEditor)]

        public async Task<bool> ConnectEthernetGateway()
        {
            SystemController.DisconnectGateway();

            dynamic json = ReadConfig();
            json.Gateway.SerialGateway.Enable = false;
            json.Gateway.EthernetGateway.Enable = true;
            WriteConfig(json);
            configuration.Reload();

            SystemController.gatewayConfig.SerialGatewayConfig.Enable = false;
            SystemController.gatewayConfig.EthernetGatewayConfig.Enable = true;

            await Task.Run((() =>
            {
                SystemController.ConnectToGateway();
            }));

            return true;
        }


        [Authorize(UserClaims.ConfigEditor)]

        public bool DisconnectGateway()
        {
            dynamic json = ReadConfig();
            json.Gateway.SerialGateway.Enable = false;
            json.Gateway.EthernetGateway.Enable = false;
            WriteConfig(json);
            configuration.Reload();

            SystemController.gatewayConfig.SerialGatewayConfig.Enable = false;
            SystemController.gatewayConfig.EthernetGatewayConfig.Enable = false;

            SystemController.DisconnectGateway();

            return true;
        }


        [Authorize(UserClaims.ConfigEditor)]

        public bool StartNodesEngine()
        {
            dynamic json = ReadConfig();
            json.NodesEngine.Enable = true;
            WriteConfig(json);
            configuration.Reload();

            SystemController.nodesEngine.Start();

            return true;
        }



        [Authorize(UserClaims.ConfigEditor)]

        public bool StopNodesEngine()
        {
            dynamic json = ReadConfig();
            json.NodesEngine.Enable = false;
            WriteConfig(json);
            configuration.Reload();

            SystemController.nodesEngine.Stop();

            return true;
        }


        public WebServerInfo GetWebServerInfo()
        {
            if (SystemController.usersDb == null)
                return null;

            WebServerInfo info = new WebServerInfo();
            info.RegisteredUsersCount = SystemController.usersDb.GetUsersCount();

            return info;
        }



        [HttpGet]
        public IActionResult Rules()
        {
            return View(SystemController.webServerRules);
        }



        [Authorize(UserClaims.ConfigEditor)]

        [HttpPost]
        public IActionResult Rules(WebServerRules model)
        {
            if (model != null)
            {
                SystemController.webServerRules = model;

                dynamic json = ReadConfig();
                json.WebServer.Rules = JObject.FromObject(model);
                WriteConfig(json);
                configuration.Reload();
            }

            return RedirectToAction("Index");
        }



        [HttpGet]
        public IActionResult Server()
        {
            return View(SystemController.webServerConfig);
        }



        [Authorize(UserClaims.ConfigEditor)]

        [HttpPost]
        public IActionResult Server(WebServerConfig model)
        {
            if (model != null)
            {
                SystemController.webServerConfig = model;

                dynamic json = ReadConfig();
                json.WebServer.Address = model.Address;
                WriteConfig(json);

                json= JObject.Parse(System.IO.File.ReadAllText(project_file));
                json.commands.web = $"Microsoft.AspNet.Server.Kestrel --server.urls {model.Address}";
                System.IO.File.WriteAllText(project_file, json.ToString());

                configuration.Reload();
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult NodeEditor()
        {
            return View(SystemController.nodeEditorConfig);
        }


        [Authorize(UserClaims.ConfigEditor)]

        [HttpPost]
        public IActionResult NodeEditor(NodeEditorConfig model)
        {
            dynamic json = ReadConfig();
            json.NodeEditor = JObject.FromObject(model);
            WriteConfig(json);
            configuration.Reload();

            SystemController.nodeEditorConfig = model;

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult NodesEngine()
        {
            return View(SystemController.nodesEngineConfig);
        }


        [Authorize(UserClaims.ConfigEditor)]

        [HttpPost]
        public IActionResult NodesEngine(NodesEngineConfig model)
        {
            model.Enable = SystemController.nodesEngine.IsStarted();

            if (model.UpdateInterval < 0)
                model.UpdateInterval = 0;

            dynamic json = ReadConfig();
            json.NodesEngine = JObject.FromObject(model);
            WriteConfig(json);
            configuration.Reload();

            SystemController.nodesEngineConfig = model;
            SystemController.nodesEngine.SetUpdateInterval(model.UpdateInterval);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Console()
        {
            return View(SystemController.logs.consoleConfig);
        }


        [Authorize(UserClaims.ConfigEditor)]

approot/src/WebController/Controllers/DashboardController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Configuration;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.DashboardObserver)]
    public class DashboardController : Controller
    {
        const string MAIN_PANEL_ID = "Main";
        const string HOME_PANEL_ID = "Home";

        private UiNodesEngine engine = SystemController.uiNodesEngine;


        public IActionResult Index()
        {
            ViewBag.panelId = HOME_PANEL_ID;

            return View();
        }



        public IActionResult Panel(string id)
        {
            if (engine == null)
                return HttpBadRequest();

            if (id == null || id == MAIN_PANEL_ID)
            {
                id = MAIN_PANEL_ID;
                ViewBag.panelName = "Main Panel";
            }
            else
            {
                PanelNode panel = engine.GetPanel(id);
                if (panel == null)
                    return HttpNotFound();
                ViewBag.panelName = panel.Settings["Name"].Value;
            }

            ViewBag.panelId = id;
            return View("Index");
        }

        public IActionResult List()
        {
            if (engine == null)
                return HttpBadRequest();

            ViewBag.showMainPanel = engine.GetUINodesForPanel(MAIN_PANEL_ID).Any();

            List<PanelNode> allPanels = engine.GetPanels();
            List<PanelNode> notEmptyPanels = new List<PanelNode>();
            foreach (var panel in allPanels)
            {
                if (engine.GetUINodesForPanel(panel.Id).Any())
                    notEmptyPanels.Add(panel);
            }

            return View(notEmptyPanels);
        }


        
        public IActionResult Chart(string id, string autoscroll, string style, string start, string end)
        {
            if (engine == null)
                return HttpBadRequest();

            UiChartNode node = engine.GetUINode(id) as UiChartNode;
            if (node == null)
                return new HttpNotFoundResult();

            ViewBag.autoscroll = autoscroll;

            if (style == null)
                style = node.Style;

            ViewBag.style = style;
            ViewBag.start = start ?? "0";
            ViewBag.end = end ?? "0";
            ViewBag.panelId = node.PanelId;

            return View(node);
        }
    }
}

approot/src/WebController/Controllers/HardwareController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Authorization;
using MyNodes.Gateways.MySensors;
using MyNodes.Users;
using MyNodes.WebController.Code;


namespace MyNodes.WebController.Controllers
{


    [Authorize(UserClaims.HardwareObserver)]

    public class HardwareController : Controller
    {
        private IMySensorsRepository mySensorsDb;

        public HardwareController()
        {
            mySensorsDb = SystemController.mySensorsDb;
        }

        public ActionResult Index()
        {
            return View();
        }





        public ActionResult SettingsSelect()
        {
            var nodes = mySensorsDb.GetNodes();
            return View(nodes);
        }



        [HttpGet]
        public ActionResult Settings(int? id)
        {
            if (id == null)
                return RedirectToAction("SettingsSelect");

            Node node = mySensorsDb.GetNode(id.Value);
            if (node == null)
                return HttpNotFound();

            return View(node);
        }


        [Authorize(UserClaims.EditorEditor)]

        [HttpPost]
        public ActionResult Settings()
        {
            int id = Int32.Parse(Request.Form["Id"]);
            Node node = mySensorsDb.GetNode(id);
            string nodename = Request.Form["nodename"];
            if (nodename == "")
                nodename = null;
            node.name = nodename;
            foreach (var sensor in node.sensors)
            {

                string sensordescription = Request.Form["sensordescription-" + sensor.sensorId];
                if (sensordescription == "")
                    sensordescription = null;
                sensor.description = sensordescription;

            }
            mySensorsDb.UpdateNode(node);

            GatewayAPIController gatewayApi = new GatewayAPIController();
            gatewayApi.UpdateNodeSettings(node);


            return RedirectToAction("Index");
            // return View(node);
        }


        [Authorize(UserClaims.EditorEditor)]

        public ActionResult Remove(int id)
        {
            Node node = mySensorsDb.GetNode(id);
            if (node == null)
                return HttpNotFound();


            GatewayAPIController gatewayApi = new GatewayAPIController();
            gatewayApi.RemoveNode(node.Id);

            mySensorsDb.RemoveNode(node.Id);


            return RedirectToAction("Index");
        }
    }
}

approot/src/WebController/Controllers/LogsController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.LogsObserver)]

    public class LogsController:Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Show",new { id = "System"});
        }


        public IActionResult Show(string id)
        {
            ViewBag.LogType = id;
            ViewBag.PageName = id;

            switch (id)
            {
                case "GatewayState":
                    ViewBag.PageName = "Gateway State";
                    break;
                case "GatewayMessages":
                    ViewBag.PageName = "Gateway Messages";
                    break;
                case "GatewayDecodedMessages":
                    ViewBag.PageName = "Gateway Decoded Messages";
                    break;
                case "NodesEngine":
                    ViewBag.PageName = "Nodes Engine";
                    break;
            }

            return View();
        }
        
        



        public List<LogRecord> GetLogs(string logType)
        {
            if (logType == "All")
                return SystemController.logs.GetAllLogs();

            if (logType == "Errors")
                return SystemController.logs.GetErrorsLogs();

            LogRecordSource source;
            bool result = LogRecordSource.TryParse(logType, out source);
            if (!result)
                return null;

            return SystemController.logs.GetLogsOfSource(
                (LogRecordSource)Enum.Parse(typeof(LogRecordSource), logType));
        }



        [Authorize(UserClaims.LogsEditor)]

        public bool ClearLogs(string logType)
        {
            if (logType == "All")
            {
                SystemController.logs.ClearAllLogs();
                return true;
            }

            SystemController.logs.ClearLogsOfSource(
                (LogRecordSource)Enum.Parse(typeof(LogRecordSource), logType));
  

            return true;
        }
        

    }
}

approot/src/WebController/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link href="~/lib/animate.css/animate.css" rel="stylesheet" />
        @*<link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />*@
        <link href="~/lib/semantic-ui/dist/semantic.css" rel="stylesheet" />
        <link href="~/css/daterangepicker/daterangepicker.css" rel="stylesheet" />
        <link href="~/css/slider/nouislider.css" rel="stylesheet" />
        <link href="~/css/switch/switch.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("styles", required: false)
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
        @* <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />*@
        <link href="~/lib/semantic-ui/dist/semantic.min.css" rel="stylesheet" />
        <link href="~/css/daterangepicker/daterangepicker.min.css" rel="stylesheet" />
        <link href="~/css/slider/nouislider.css" rel="stylesheet" />
        <link href="~/css/switch/switch.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("styles", required: false)
    </environment>
</head>
<body>


    <!-- Sidebar Menu -->
    <div class="ui inverted vertical menu sidebar thin">
        <div class="ui container">
            <a asp-controller="Dashboard" asp-action="Index" class="item fadebefore">Dashboard</a>
            <a asp-controller="Hardware" asp-action="Index" class="item fadebefore">Hardware</a>
            <a asp-controller="Logs" asp-action="Index" class="item fadebefore">Logs</a>
            <a asp-controller="Config" asp-action="Index" class="item fadebefore">Config</a>
            <a asp-controller="Home" asp-action="About" class="item fadebefore">About</a>
        </div>
    </div>






    <!-- Header Menu-->
    <div class="ui fixed big borderless main menu">
        <div class="ui container">
            <a class="sidebar-button showsmall item">
                <i class="sidebar icon"></i>
            </a>

            <a asp-controller="Home" asp-action="About" class="ui item fadebefore"><h3>MyNodes.NET</h3></a>

        </div>
    </div>


    <div class="pusher">
        <br />
        <br />
        <br />

        @RenderBody()


    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/noty/js/noty/packaged/jquery.noty.packaged.js"></script>
        <script src="~/lib/moment/moment.js"></script>
        <script src="~/js/handlebars.js"></script>
        <script src="~/lib/semantic-ui/dist/semantic.js"></script>
        <script src="~/js/daterangepicker/daterangepicker.js"></script>
        <script src="~/js/slider/nouislider.js"></script>
        <script asp-src-include="~/lib/signalr/jquery.signalr.js"></script>
        <script src="~/signalr/hubs" type="text/javascript"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>

        <script src="~/lib/noty/js/noty/packaged/jquery.noty.packaged.min.js"></script>
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/js/handlebars.min.js"></script>
        <script src="~/lib/semantic-ui/dist/semantic.min.js"></script>
        <script src="~/js/daterangepicker/daterangepicker.js"></script>
        <script src="~/js/slider/nouislider.min.js"></script>
        <script asp-src-include="~/lib/signalr/jquery.signalr.js"></script>
        <script src="~/signalr/hubs" type="text/javascript"></script>
    </environment>

    @RenderSection("scripts", required: false)

    <script>
        ////page fade animation
        //$('.body-content').fadeIn(700);
        //$('#footer').fadeIn(700);

        //$('.fadebefore').click(function () {
        //    var href = $(this).attr('href');

        //    // do animation
        //    $('.body-content').fadeOut(400, function () {
        //        // go to link when animation completes
        //        window.location = href;

        //    });

        //    // over ride browser following link when clicked
        //    return false;
        //});


        // noty settings
        $.noty.defaults.layout = 'bottomRight';
        $.noty.defaults.theme = 'relax';
        $.noty.defaults.timeout = 3000;
        $.noty.defaults.animation = {
            open: 'animated bounceInRight', // Animate.css class names
            close: 'animated flipOutX', // Animate.css class names
            easing: 'swing', // unavailable - no need
            speed: 500 // unavailable - no need
        };


        $(document)
    .ready(function () {

        // show dropdown
        $('.ui.dropdown').dropdown({
            on: 'click'
        });

        // create sidebar and attach to menu open
        $('.ui.sidebar')
            .sidebar('attach events', '.sidebar-button');
    });


    </script>
</body>
</html>

approot/src/WebController/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link href="~/lib/animate.css/animate.css" rel="stylesheet" />
        @*<link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />*@
        <link href="~/lib/semantic-ui/dist/semantic.css" rel="stylesheet" />
        <link href="~/css/daterangepicker/daterangepicker.css" rel="stylesheet" />
        <link href="~/css/slider/nouislider.css" rel="stylesheet" />
        <link href="~/css/switch/switch.css" rel="stylesheet" />
        @RenderSection("styles", required: false)
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
        @*  <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />*@
        <link href="~/lib/semantic-ui/dist/semantic.min.css" rel="stylesheet" />
        <link href="~/css/daterangepicker/daterangepicker.min.css" rel="stylesheet" />
        <link href="~/css/slider/nouislider.css" rel="stylesheet" />
        <link href="~/css/switch/switch.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("styles", required: false)
    </environment>
</head>
<body>


    <!-- Sidebar Menu -->
    <div class="ui inverted vertical menu sidebar thin">
        <div class="ui container">
            <a asp-controller="Dashboard" asp-action="Index" class="item fadebefore">Dashboard</a>
            <a asp-controller="Hardware" asp-action="Index" class="item fadebefore">Hardware</a>
            <a asp-controller="Logs" asp-action="Index" class="item fadebefore">Logs</a>
            <a asp-controller="Config" asp-action="Index" class="item fadebefore">Config</a>
            <a asp-controller="Home" asp-action="About" class="item fadebefore">About</a>
        </div>
    </div>






    <!-- Header Menu-->
    <div class="ui fixed big borderless main menu">
        <div class="ui container">
            <a class="sidebar-button showsmall item">
                <i class="sidebar icon"></i>
            </a>

            <a asp-controller="Home" asp-action="About" class="ui item fadebefore"><h3>MyNodes.NET</h3></a>

            <a asp-controller="Dashboard" asp-action="Index" class="item hidesmall fadebefore">Dashboard</a>
            <a asp-controller="Hardware" asp-action="Index" class="ui item hidesmall fadebefore">Hardware</a>
            <a asp-controller="Logs" asp-action="Index" class="ui item hidesmall fadebefore">Logs</a>
            <a asp-controller="Config" asp-action="Index" class="ui item hidesmall fadebefore">Config</a>


            <div class="right menu">
                <div class="item">
                    @{
                        if (User != null && User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="User" asp-action="Logout" class="ui button fadebefore">Logout</a>
                        }
                        else
                        {
                            <a asp-controller="User" asp-action="Login" class="ui primary button fadebefore">Login</a>
                        }
                    }
                </div>
            </div>


        </div>
    </div>


    <div class="pusher">
        <br />
        <br />
        <br />

        @RenderBody()


    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/noty/js/noty/packaged/jquery.noty.packaged.js"></script>
        <script src="~/lib/moment/moment.js"></script>
        <script src="~/js/handlebars.js"></script>
        <script src="~/lib/semantic-ui/dist/semantic.js"></script>
        <script src="~/js/daterangepicker/daterangepicker.js"></script>
        <script src="~/js/slider/nouislider.js"></script>
        <script asp-src-include="~/lib/signalr/jquery.signalr.js"></script>
        <script src="~/signalr/hubs" type="text/javascript"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>

        <script src="~/lib/noty/js/noty/packaged/jquery.noty.packaged.min.js"></script>
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/js/handlebars.min.js"></script>
        <script src="~/lib/semantic-ui/dist/semantic.min.js"></script>
        <script src="~/js/daterangepicker/daterangepicker.js"></script>
        <script src="~/js/slider/nouislider.min.js"></script>
        <script asp-src-include="~/lib/signalr/jquery.signalr.js"></script>
        <script src="~/signalr/hubs" type="text/javascript"></script>
    </environment>

    @RenderSection("scripts", required: false)

    <script>
        ////page fade animation
        //$('.body-content').fadeIn(700);
        //$('#footer').fadeIn(700);

        //$('.fadebefore').click(function () {
        //    var href = $(this).attr('href');

        //    // do animation
        //    $('.body-content').fadeOut(400, function () {
        //        // go to link when animation completes
        //        window.location = href;

        //    });

        //    // over ride browser following link when clicked
        //    return false;
        //});


        // noty settings
        $.noty.defaults.layout = 'bottomRight';
        $.noty.defaults.theme = 'relax';
        $.noty.defaults.timeout = 3000;
        $.noty.defaults.animation = {
            open: 'animated bounceInRight', // Animate.css class names
            close: 'animated flipOutX', // Animate.css class names
            easing: 'swing', // unavailable - no need
            speed: 500 // unavailable - no need
        };


        $(document)
    .ready(function () {

        // show dropdown
        $('.ui.dropdown').dropdown({
            on: 'click'
        });

        // create sidebar and attach to menu open
        $('.ui.sidebar')
            .sidebar('attach events', '.sidebar-button');
    });


    </script>
</body>
</html>