approot/src/WebController/ViewModels/NodeEditor/NodeDescription.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyNodes.WebController.ViewModels.NodeEditor
{
    public class NodeDescription
    {
        public string category;
        public string type;
        public string description;
    }
}

approot/src/WebController/Controllers/DashboardController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Configuration;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;

namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.DashboardObserver)]
    public class DashboardController : Controller
    {
        const string MAIN_PANEL_ID = "Main";
        const string HOME_PANEL_ID = "Home";

        private UiNodesEngine engine = SystemController.uiNodesEngine;


        public IActionResult Index()
        {
            ViewBag.panelId = HOME_PANEL_ID;

            return View();
        }



        public IActionResult Panel(string id)
        {
            if (engine == null)
                return HttpBadRequest();

            if (id == null || id == MAIN_PANEL_ID)
            {
                id = MAIN_PANEL_ID;
                ViewBag.panelName = "Main Panel";
            }
            else
            {
                PanelNode panel = engine.GetPanel(id);
                if (panel == null)
                    return HttpNotFound();
                ViewBag.panelName = panel.Settings["Name"].Value;
            }

            ViewBag.panelId = id;
            return View("Index");
        }

        public IActionResult List()
        {
            if (engine == null)
                return HttpBadRequest();

            ViewBag.showMainPanel = engine.GetUINodesForPanel(MAIN_PANEL_ID).Any();

            List<PanelNode> allPanels = engine.GetPanels();
            List<PanelNode> notEmptyPanels = new List<PanelNode>();
            foreach (var panel in allPanels)
            {
                if (engine.GetUINodesForPanel(panel.Id).Any())
                    notEmptyPanels.Add(panel);
            }

            return View(notEmptyPanels);
        }


        
        public IActionResult Chart(string id, string autoscroll, string style, string start, string end)
        {
            if (engine == null)
                return HttpBadRequest();

            UiChartNode node = engine.GetUINode(id) as UiChartNode;
            if (node == null)
                return new HttpNotFoundResult();

            ViewBag.autoscroll = autoscroll;

            if (style == null)
                style = node.Style;

            ViewBag.style = style;
            ViewBag.start = start ?? "0";
            ViewBag.end = end ?? "0";
            ViewBag.panelId = node.PanelId;

            return View(node);
        }
    }
}

approot/src/WebController/Controllers/NodeEditorController.cs
/*  MyNodes.NET 
    Copyright (C) 2016 Derwish <derwish.pro@gmail.com>
    License: http://www.gnu.org/licenses/gpl-3.0.txt  
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using MyNodes.Gateways;
using LiteGraph;
using Microsoft.AspNet.Authorization;
using Microsoft.Extensions.Configuration;
using MyNodes.Repositories.EF.SQLite;
using MyNodes.Nodes;
using MyNodes.Users;
using MyNodes.WebController.Code;
using MyNodes.WebController.ViewModels.NodeEditor;
using Newtonsoft.Json;
using Node = MyNodes.Nodes.Node;


namespace MyNodes.WebController.Controllers
{
    [Authorize(UserClaims.EditorObserver)]
    public class NodeEditorController : Controller
    {
        const string MAIN_PANEL_ID = "Main";

        private NodesEngine engine = SystemController.nodesEngine;


        public IActionResult Index(bool split)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");

            ViewBag.split = split;
            ViewBag.panelId = MAIN_PANEL_ID;

            ViewBag.Theme = SystemController.nodeEditorConfig.Theme;

            return View();
        }

        public IActionResult Panel(string id, bool split)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");


            ViewBag.split = split;

            if (id == null || id == MAIN_PANEL_ID)
                return RedirectToAction("Index");

            PanelNode panel = engine.GetPanelNode(id);

            if (panel == null)
                return HttpNotFound();

            ViewBag.panelId = panel.Id;
            ViewBag.ownerPanelId = panel.PanelId;

            //create menu stack
            List<PanelNode> panelsStack = new List<PanelNode>();

            bool findNext = true;
            while (findNext)
            {
                panelsStack.Add(panel);
                if (panel.PanelId == MAIN_PANEL_ID)
                    findNext = false;
                else
                {
                    panel = engine.GetPanelNode(panel.PanelId);
                }
            }

            panelsStack.Reverse();
            ViewBag.panelsStack = panelsStack;

            ViewBag.Theme = SystemController.nodeEditorConfig.Theme;


            return View("Index");
        }


        public IActionResult Split(string id)
        {
            if (engine == null)
                return View("Error", "Nodes Engine is not started.<br/><br/>   <a href='/Config'>Check settings</a>");

            if (id == null)
                ViewBag.route = "";
            else
                ViewBag.route = "Panel/" + id;
            return View();
        }

        public IActionResult NodesDescription()
        {
            List<Nodes.Node> nodes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(s => s.GetTypes())
                 .Where(t => t.IsSubclassOf(typeof(Nodes.Node)) && !t.IsAbstract)
                .Select(t => (Nodes.Node)Activator.CreateInstance(t)).ToList();

            nodes = nodes.OrderBy(x => x.Category + x.Type).ToList();

            List<NodeDescription> descrition = nodes.Select(node => new NodeDescription
            {
                category = node.Category,
                type = node.Type,
                description = node.GetNodeDescription()
            }).ToList();

            return View(descrition);
        }
    }
}

approot/src/WebController/Views/NodeEditor/Index.cshtml
@using MyNodes.Nodes
@{
    Layout = null;
    ViewBag.Title = "Node Editor";

    int theme = ViewBag.Theme ?? 1;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>



    <link href="~/lib/semantic-ui/dist/semantic.min.css" rel="stylesheet" />
    <link href="~/lib/animate.css/animate.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/css/litegraph.css">
    <link rel="stylesheet" type="text/css" href="~/css/litegraph-editor.css">
    <link rel="stylesheet" type="text/css" href="@Html.Raw($"~/css/litegraph-theme" +theme+".css")">
    <link rel="stylesheet" type="text/css" href="~/css/site-black.css">
</head>
<body>

    <!-- Header Menu-->
    <div class="ui inverted fixed big borderless main menu">
        <div class="ui container">
            <a asp-controller="Home" asp-action="About" class="ui item fadebefore"><h3>MyNodes.NET</h3></a>
            <div class="right menu">

            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <div class="ui container">

        <p>
            @if (@ViewBag.panelId == "Main")
            {
                <a asp-controller="Dashboard" asp-action="Index" target="_top" class="ui inverted small basic right floated button">Dashboard</a>
                if (ViewBag.split == true)
                {
                    <a asp-action="Index" target="_top" class="ui inverted small basic right floated button">Split</a>
                }
                else
                {
                    <a asp-action="Split" target="_top" class="ui inverted small basic right floated button">Split</a>
                }
            }
            else
            {
                <a asp-controller="Dashboard" asp-action="Panel" asp-route-id="@ViewBag.panelId" target="_top" class="ui inverted small basic right floated button">Dashboard</a>
                if (ViewBag.split == true)
                {
                    <a asp-action="Panel" asp-route-id="@ViewBag.panelId" target="_top" class="ui inverted small basic right floated button">Split</a>
                }
                else
                {
                    <a asp-action="Split" asp-route-id="@ViewBag.panelId" target="_top" class="ui inverted small basic right floated button">Split</a>
                }
            }

            <div class="ui tiny buttons">
                <a asp-controller="NodeEditor" asp-action="Index" class="ui inverted tiny basic button">Main Panel</a>
                @{
                    List<PanelNode> panelsStack = ViewBag.panelsStack;
                    if (panelsStack != null && panelsStack.Any())
                    {
                        foreach (PanelNode panel in panelsStack)
                        {
                            <a asp-action="Panel" asp-route-id="@panel.Id" class="ui inverted tiny basic button">@panel.Settings["Name"].Value</a>
                        }
                    }
                }
            </div>
    </div>
    <br />
    <div id="main"></div>

    <div class="ui small modal" id="node-settings-panel">
        <div class="header" id="node-settings-title"></div>
        <div class="content">
            <div class="ui form" id="node-settings-body">
            </div>
        </div>
        <div class="actions">
            <div class="ui cancel button">
                Cancel
            </div>
            <div class="ui ok blue button">
                OK
            </div>
        </div>
    </div>

    <div class="ui small modal" id="import-panel">
        <div class="header" id="import-panel-title"></div>
        <div class="content" id="import-panel-body">
            <form class="ui form" name="uploadForm">
                <div class="fields">
                    <div class="field">
                        File: <input type="file" name="uploadFile" id="uploadFile">
                    </div>
                </div>
            </form>
        </div>
        <div class="content" id="import-panel-message"></div>
        <div class="actions">
            <div class="ui cancel button">
                Cancel
            </div>
        </div>
    </div>


    <div class="ui small modal" id="modal-panel">
        <div class="header" id="modal-panel-title"></div>
        <div class="content">
            <form class="ui form" id="modal-panel-form"></form>
            <div class="ui message" id="modal-panel-message" style="display: none"></div>
        </div>
        <div class="actions">
            <div class="ui cancel button">Cancel</div>
            <div class="ui button" id="modal-panel-submit" style="display: none">OK</div>
        </div>
    </div>




    <script id="textSettingTemplate" type="text/x-handlebars-template">
        @*<div class="ui attached basic segment">*@
        <div class="field">
            <label> {{Label}} </label>
            <input type="text" id="node-setting-{{Key}}" value="{{Value}}">
        </div>
        @*</div>*@
    </script>

    <script id="numberSettingTemplate" type="text/x-handlebars-template">
        @*<div class="ui attached basic segment">*@
        <div class="field">
            <label> {{Label}} </label>
            <input type="number" id="node-setting-{{Key}}" value="{{Value}}">
        </div>
        @*</div>*@
    </script>

    <script id="checkboxSettingTemplate" type="text/x-handlebars-template">
        @*<div class="ui attached basic segment">*@
        <div class="field">
            <div class="ui toggle checkbox">
                <input type="checkbox" name="public" id="node-setting-{{Key}}" value="true">
                <label> {{Label}} </label>
            </div>
        </div>
        @*</div>*@
    </script>



    <script>
        //this var used in litegraph.js
        var this_panel_id = "@ViewBag.panelId";
        var owner_panel_id = "@ViewBag.ownerPanelId";
    </script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/handlebars.min.js"></script>
    <script src="~/lib/semantic-ui/dist/semantic.min.js"></script>
    <script src="~/lib/noty/js/noty/packaged/jquery.noty.packaged.min.js"></script>
    <script type="text/javascript" src="~/js/node-editor/litegraph.js"></script>
    <script type="text/javascript" src="~/js/node-editor/litegraph-editor.js"></script>
    <script type="text/javascript" src="@Html.Raw("~/js/node-editor/node-editor-theme"+theme+".js")"></script>
    <script type="text/javascript" src="~/js/node-editor/node-editor-list.js"></script>
    <script type="text/javascript" src="~/js/node-editor/node-editor-signalr.js"></script>
    <script asp-src-include="~/lib/signalr/jquery.signalr.js"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>


</body>
</html>

approot/src/WebController/Views/NodeEditor/NodesDescription.cshtml
@using System.Threading.Tasks
@using MyNodes.WebController.ViewModels.NodeEditor
@model List<MyNodes.WebController.ViewModels.NodeEditor.NodeDescription>

@{
    ViewBag.Title = "Nodes Description";
    string category="";
}

<br />
<div class="ui container">

    <h2>@ViewBag.Title</h2>

    <div>
       < <a asp-action="Index">Node Editor</a>
    </div>
    <div class="ui divider"></div>


    <div class="ui four column grid" id="nodesContainer">
    </div>


</div>
<br />

<div class="ui text container">
    @foreach (NodeDescription n in Model)
    {
        if (category != n.category)
        {
            category = n.category;
            <br/>
            <br/>
            <h1>@category</h1>
        }
        <h3>@n.type</h3>
        <p>
           @Html.Raw(n.description)
        </p>
    }

</div>


<br />
<br />

approot/src/WebController/Views/NodeEditor/Split.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN//3.2">
<HTML>
<HEAD>
    <title>MyNodes.NET</title>
</HEAD>
    <FRAMESET cols="400px,*">
        <FRAME name="dashboard" src="/Dashboard/@ViewBag.route" scrolling="AUTO">
        <FRAME name="editor" src="/NodeEditor/@ViewBag.route?split=true" scrolling="AUTO">
    </FRAMESET>
</HTML>